- name: demo on filters
  hosts: localhost
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
  tasks:  
    - name: convert sting to list
      debug:
        msg: "Topics acre: {{topics | split(',')}}"