- name: demo on filters
  hosts: localhost
  connection: local
  vars:
    topics: Linux, Shell, Ansible, Terraform
    tagMap:
      name: Ansible
      project: roboshop
      environment: dev
  tasks:  
    - name: convert sting to list
      debug:
        msg: "Topics acre: {{topics | split(',')}}"

    - name: set default value
      debug:
        msg: "Hi {{ GREETINGS | default('Good morning')}}"        

    - name: convert map to list
      debug:
        msg: "{{tagMap | dict2items }}"    