- name: demo on shell vs commond
  hosts: localhost
  connection: local
  tasks:
  - name: command test
     #command: cat /etc/passwd | grep root
    shell: cat /etc/passwd | grep root
    register: users_output

  - name: pring out put
    debug:
      msg:"{{ users_ootput }}"

  - name: list files
   #command: ls -ltr > /tmp/files.txt
    shell: ls -ltr > /tmp/files.txt       
    